#!/bin/sh
exec tail -n +3 $0
# This file provides an easy way to add custom menu entries.  Simply type the
# menu entries you want to add after this comment.  Be careful not to change
# the 'exec tail' line above.
menuentry 'Grub Legacy' {
    set root='(hd0,msdos1)'
    chainloader +1
}
menuentry 'Windows 7' {
    set root='(hd0,msdos3)'
    chainloader +1
}
